-- ==============================================================================
-- SCRIPT DE CORREÇÃO GERAL DO BANCO DE DADOS (Rode isso TUDO no SQL Editor do Supabase)
-- ==============================================================================

-- 1. CORREÇÃO DA TABELA COURSES (Para salvar aulas e módulos)
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS modules jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS tags text[] DEFAULT '{}';
ALTER TABLE public.courses ADD COLUMN IF NOT EXISTS total_duration integer DEFAULT 0;

-- 2. CRIAÇÃO DA TABELA DE LAYOUT (Para salvar o construtor da Home)
CREATE TABLE IF NOT EXISTS public.layout_blocks (
    id bigint generated by default as identity primary key,
    blocks jsonb DEFAULT '[]'::jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insere uma linha inicial se não existir (ID 1 fixo para o layout principal)
INSERT INTO public.layout_blocks (id, blocks)
VALUES (1, '[]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Habilita RLS (segurança) mas permite tudo para este caso (simplificação)
ALTER TABLE public.layout_blocks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users" ON public.layout_blocks
FOR ALL USING (true) WITH CHECK (true);

-- 3. CORREÇÃO DO PERFIL DE USUÁRIO (Para salvar instagram, telefone, etc)
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS company_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS instagram text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone text;

-- 4. TABELA DE COMENTÁRIOS (Caso não exista)
CREATE TABLE IF NOT EXISTS public.comments (
    id text PRIMARY KEY,
    lesson_id text NOT NULL,
    user_id uuid REFERENCES auth.users(id),
    user_name text,
    user_avatar text,
    text text,
    status text DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
    likes integer DEFAULT 0,
    liked_by text[] DEFAULT '{}'
);

-- Habilita RLS para comments
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all access for all users comments" ON public.comments
FOR ALL USING (true) WITH CHECK (true);
